# Generated by Django 3.2.9 on 2021-11-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20211110_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='habilidades',
            field=models.ManyToManyField(to='personal.Habilidades'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='first_mane',
            field=models.CharField(help_text='Nombre', max_length=60, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='last_name',
            field=models.CharField(help_text='apellido', max_length=60, verbose_name='Apellidos'),
        ),
    ]
