# Generated by Django 3.2.9 on 2021-11-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20211110_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name': 'Empleados', 'verbose_name_plural': 'Mis Empleados'},
        ),
    ]
