# Generated by Django 3.2.9 on 2021-11-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_empleados_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='first_mane',
            new_name='first_name',
        ),
    ]
