# Generated by Django 3.2.9 on 2021-11-11 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_rename_first_mane_empleados_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='Textoo'),
            preserve_default=False,
        ),
    ]
