# Generated by Django 3.2.9 on 2021-11-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_empleados_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='full_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre Completo'),
        ),
    ]
